README.md
index.js

When there is an error communicating with ChatGPT, such as a message exceeding the length limit, the error code is not currently being sent. This makes it difficult to determine the cause of the error and handle it properly. 
In this PR I'm sending the prop `code` with the one received from ChatGPT.
For example, when the message length exceeds the limit,, we get this response from a 413, but we are not currently using it:
```js
{
message: 'The message you submitted was too long, please reload the conversation and submit something shorter.',
code: 'message_length_exceeds_limit'
}
```
With this suggested change, we'll be able to handle specific errors by reading the `code` prop and act accordingly.

feat: send error code from ChatGPT along with error message

---

index.js

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
at new NodeError (node:internal/errors:400:5)
at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1055:11)
at defaultResolve (node:internal/modules/esm/resolve:1135:3)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ESMLoader.import (node:internal/modules/esm/loader:525:22)
at importModuleDynamically (node:internal/modules/esm/translators:110:35)
at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
at …
```

fix(settings): ERR_UNSUPPORTED_ESM_URL_SCHEME errors on windows

---

README.md
index.js

Unfortunately, the error code is not being returned from `sendMessage` (it's only logged, not sure why), so we can't use it at this moment. I requested this feature here https://github.com/transitive-bullshit/chatgpt-api/issues/272
I'll be following the thread so we can add it when possible.
Reverts waylaidwanderer/node-chatgpt-api#7

Revert "feat: send error code from ChatGPT along with error message"

---

bin/server.js

This will allow for a standalone Docker build. And is a part of attempting to resolve issue #3.
See my [repo](https://github.com/queercat/gpt-api-docker) that resolves #3 once this is resolved. 
The reason this isn't working is docker cannot support the 127.0.0.1 binding only 0.0.0.0 (which Fastify prefers anyway afaik.)

fix(client): updated fastify host binding to support proper docker deployment

---

src/ChatGPTBrowserClient.js
src/ChatGPTClient.js

The event may be like this, and then a json parse exception occurred.
`{
data: '2023-02-20 08:40:33.556053',
event: 'ping',
id: '',
retry: undefined
}`

BugFix:The event may be ping, and  a json parse exception occurred

---

src/ChatGPTBrowserClient.js

This will double check conversation in case conversationsCache not exists.

fix(browser-client): avoid cache null data

---

README.md
bin/server.js
settings.example.js

Since we were unable to use bing client to continue the conversation when we need to use sydney (cacheOptions wasn't set when invoking BingAIClient). I've added sydney client as a seperate option in settings.js

fix(server): jailbreak conversation cache fix

---

README.md

Adding my own project that using node-chatgpt-api.
My project is a telegram bot have these features:
- Telegram Bot (`Telegram Bot` token required)
- ChatGPT (`OpenAI` API key required)
- Bing Chat (`Bing Chat` user token required)
- Speech-to-text (`Google Cloud` API key required, or your own engine)
- Text-to-speech (`Google Cloud` API key required, or your own engine)
- Support `private` and `public` mode, with multiple authenticate methods.
- `Middleware` style workflow, easy to extend.
- Realtime stream-style response, no more waiting.
- Markdown rendering for GhatGPT
- Reference rendering for Bing Chat
- Code block rendering, developers friendly.
- ESM from the ground up

docs(readme): add halbot

---

src/BingAIClient.js

When IP is blocked by BingAI, user will receive HTTP code 200 with wrong content-length header ( 0 or 1 in my case ) https://twitter.com/likev/status/1625866805653954560

fix(bing): check if IP is blocked by Bing

---

src/BingAIClient.js

Event handler on WebSocket for 'error' event needs to be set up a bit earlier.
node:events:368
throw er; // Unhandled 'error' event
^
Error: Unexpected server response: 503
at ClientRequest.<anonymous> (/node-chatgpt-api/node_modules/ws/lib/websocket.js:888:7)
at ClientRequest.emit (node:events:390:28)
at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
at TLSSocket.socketOnData (node:_http_client:487:22)
at TLSSocket.emit (node:events:390:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
Emitted 'error' event on …

fix(bing): catch error events on WebSocket connection

---

src/BingAIClient.js

Encountered this at low probability.

fix(bing): check if eventMessage is null before setting properties

---

demos/use-browser-client.js

According to @acheong08
> For anyone who hasn't upgraded revChatGPT, please do so immediately. My domain name, [http://duti.tech](https://t.co/MbI4ivSB7a), has expired and been taken over by an unknown entity.
> 
> There could be security issues if you do not upgrade such as token logging.
> 3:27 AM · Mar 31, 2023
source: https://twitter.com/GodlyIgnorance/status/1641703845767290880?cxt=HHwWgIDRleO8wMgtAAAA
I've provided the new public proxy used in [ChatGPT-Proxy-V4](https://github.com/acheong08/ChatGPT-Proxy-V4) that is confirmed working for the browser client

fix: update reverseProxyUrl in demo, raise awareness of duti.tech compromise

---

src/BingAIClient.js

fixes https://github.com/waylaidwanderer/node-chatgpt-api/issues/263
With this method, the current user message may be moderated, but once the message is not moderated, it will not be moderated later
Summarizing multiple documents https://github.com/waylaidwanderer/node-chatgpt-api/pull/216#issuecomment-1480616340 also tested and it works

fix(bing): Try to fix everything caused by "current user message in document context"

---

src/BingAIClient.js

Hi everyone, really appreciate this project.
#264 fixed #263, but
- Now GPT-4 sees the message repeated twice: once in its normal form (in the `previousMessages` array) and once again in the garbled form with `-` and `_` inserted. This is understandably confusing, causing:
- GPT-4 to reject what looks like correct input to the user. For example, I modified the system message to play a chess game in ASCII art with the model (don't ask), and told it to reject incorrect moves. It would reject my moves many times in a row (since they looked like `Be-5`, `B_e5`, etc.)
- GPT-4 to think this is some new mode of communication, and modify its output accordingly (as demonstrated by @Naozumi520 in the comments of #264).
Dropping #264 in favor of the old "continue this conversation" prompt is …

fix(bing): use empty string for real user message in jailbreak mode

---

src/ChatGPTBrowserClient.js

Test failing was a linter error (d'oh)
from #278: 
> This is a simple proposed update but necessary for my app.
> 
> This will add the officially generated title to the response object as a promise, which keeps the operation asynchronous and allows me to await response.details.title when I need it. Can be totally ignored by those who don't need it and should keep all other operations the same.
> 
> Thought this might be the simplest way to attach the title to a response, since it only generates on the first one.
> 
> Without this, I have to do a redundant call for a title since I know we make a request to the backend api. Not to mention, my own calls cost tokens (a few but they add up) and the official titling tends to perform better.

make genTitle method async and add to response object as promise

---

src/ChatGPTBrowserClient.js

Adds an optional param to the postConversation method to handle event messages from the backend-api server, coming from sendMessage options.
I noticed while debugging that I could use the data being received during the stream from the backend-api. 
While having the tokens parsed for us is helpful for onProgress, this adds the benefit of receiving the additional data from the stream response. This PR simply adds a callback to process the data being streamed.
AbortController no longer has a default value of null as it no longer would be the last param, and a default value is being handled in L219.

feat(ChatGPTBrowserClient): add optional onEventMessage param for Browser Client

---

src/BingAIClient.js

Instead of taking Keyv options (which I had serious troubles with), just take a Keyv object. It's simpler for new Keyv users and is way more intuitive: Just pass your Keyv object as "cache" in the JSON object and do whatever while making it.

feat(bing): take a Keyv object instead of options

---

src/BingAIClient.js

fixes https://github.com/waylaidwanderer/node-chatgpt-api/issues/289 and https://github.com/waylaidwanderer/node-chatgpt-api/issues/330
have tested https://github.com/waylaidwanderer/node-chatgpt-api/pull/216#issuecomment-1480616340

Fix keeping repeating introduction due to empty message string + use a more native method to pass web page context

---

demos/use-client.js
src/ChatGPTClient.js

I was given access to Azure OpenAI and I noticed that changing the reverse proxy URL and providing the API key as mentioned in #192 would not work for me. 
The reason was that authentication is done through the 'api-key' header and not Authorization Bearer. You can authenticate an API call using an Azure Active Directory token with Auth Bearer, but as I'm not an owner of the Azure account, auth by api key is my only option. This was not clear in the repo before, and this would make it standard to authenticate by API key as shown in their docs: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference
As shown in `demos/use-client.js`, to use Azure OpenAI API with ChatGPTClient, set `azure` to true and `reverseProxyUrl` to your completion endpoint in clientOptions, …

feat(ChatGPTClient.js): add support for Azure by API key

---

src/BingAIClient.js

Bing is able to output very long messages for almost 3 minutes before ending it's answer.
Having the 2 min timout prevent the user from being able to get any long answer from Bing/Sydney. 
Pushing it to 3min (180 sec) is enough for the longest possible answer as of now.

fix(bing): extend message timeout

---

src/ChatGPTClient.js

Title. I have a need to set the Org ID, which is set in the headers:
```
curl https://api.openai.com/v1/models \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-H "OpenAI-Organization: YOUR_ORG_ID"
```
This way I can add the org ID or any other header if ever needed in the future
```
// options.header object
{
'OpenAI-Organization': `${myOrgId}`
}
```

feat(client): add support for custom headers in options object

---

bin/cli.js
package-lock.json
package.json
settings.example.js
src/BingAIClient.js

1.Import a new module '[@timefox/bic-sydney](https://github.com/timefox/node-bic-sydney)' to complete the main work of image generation for bingAiClient. The main procedure is to send the prompt returned by bing ai to bing image creator to generate the images, and then return an iframe containing the generated images.
2.Add an option to to turn on/off the image generation function of bingAiClient under 'bingAiClient/features/genImage', and disable it by default. For cli mode, it is set to false forcely.
3.Add an option to to set bingAiClient's 'x-forwarded-for' IP under 'bingAiClient/xForwardedFor'. It can be fixed, or a rand IP in a range using CIDR notation, or none. The default value is 'none'.

feat(bing): add the image generation function

---

src/BingAIClient.js

The ban check seems to no longer work (The Content-Length header is no longer added for the request when doing it from this module). Checked on Deno.
It might be wise to check the length of the response as text instead of Content-Length- that way MS can't just remove the header.

hotfix(bing): remove IP ban check (no longer working)

---

README.md

I have updated the README.md since ChatGPT Clone is now called [LibreChat](https://github.com/danny-avila/LibreChat)

Update README for LibreChat

---

src/BingAIClient.js

Increase the timeout for the Web Socket from a default of 5 seconds to 20 seconds.
The error will only really occur on peak times, but this fix will prevent any timeout error.
Will fix errors mentioned in #328 and #338.

fix(bing): increase timeout to prevent timeout error

---

src/ChatGPTClient.js

Some Azure GPT Models seem to return unexpected empty choices array, when streaming, then proceed normaly

fix(client): allow empty choices
